
[loader]
word_file = 'chen/words.lst'
tag_file = 'chen/tags.lst'
label_file = 'chen/labels.lst'
pretrained = 'chen/embeddings.txt'

[nn]
embed_units = 50
hidden_units = 1024
rescale_embeddings = true

[parser]

[train]
train_file = 'chen/wsj_02-21.sd.orig.tagged'
valid_file = 'chen/wsj_22.sd.orig.tagged'
epoch = 10000
batch_size = 10000
# init_model = ''
